### ISSUE TITLE
개요 및 TODOs

### ISSUE THREAD

**Issue by KangJunewoo** [KangJunewoo/soundpicker-server#1]
## 개요
- 서버 자체는 이미 [3주프로젝트 당시 작성했던 코드](https://github.com/SoundPicker/SoundPicker-Server)로 잘 돌아가고 있다.
- 그러나 다음 두 가지 문제를 가진다.
  - AWS 비용이 너무 많이 나온다. 서버의 트래픽이 많이 나오지 않음에도 이를 AWS의 EC2, RDS, S3를 사용하며 비용을 지불하고 있다.
  - 코드퀄리티를 하나도 고려하지 않고 짰기 떄문에 고치고 싶은 부분이 많다.

## TODOs
- [ ] 다음 사항을 고려하며 `TS + NestJS`로 재작성
  - [ ] 데이터를 RDS MySQL이 아닌, 로컬 MongoDB에 저장하도록 수정
  - [ ] 파일을 S3가 아닌, 로컬 파일시스템에 저장하도록 수정
- [ ] 오라클 클라우드로 서버 이관
  - [ ] 기존 데이터 백업 후 AWS 모든 서비스 종료
  - [ ] 오라클 클라우드에 백업해둔 데이터 세팅
